Repository eclipse-uprotocol/up-rust, pull requests merged in 2024-07, with the labels that each got.

#137 Minor QoL additions to USubscription types
  src/core/usubscription.rs
  src/uri.rs
Labels: enhancement

#138 Add unit tests for RpcClient implementation
  src/communication.rs
  src/communication/in_memory_rpc_client.rs
Labels: enhancement

#135 Add RpcServer implementation
  src/communication.rs
  src/communication/in_memory_rpc_server.rs
  src/communication/rpc.rs
  src/umessage.rs
  src/uri.rs
Labels: enhancement

#139 Expose the useful consts in UUri
  src/uri.rs
Labels: enhancement

#140 Add UTransport based L2 Notification API implementation
  src/communication.rs
  src/communication/default_notifier.rs
  src/communication/notification.rs
  src/uattributes.rs
  src/umessage.rs
Labels: enhancement

#141 Update MSRV to 1.74
  Cargo.toml
Labels: bug

#142 Minor derive additions to proto types
  src/communication.rs
Labels: enhancement

#145 Add automock attributes to commonly used traits
  src/communication/default_notifier.rs
  src/communication/in_memory_rpc_client.rs
  src/communication/in_memory_rpc_server.rs
  src/communication/notification.rs
  src/communication/rpc.rs
  src/utransport.rs
Labels: enhancement

#146 Add RpcClient based implementation of USubscription
  Cargo.toml
  src/communication.rs
  src/communication/usubscription_client.rs
  src/core/usubscription.rs
  src/lib.rs
Labels: enhancement

#148 Improve test coverage of helper functions
  src/uattributes.rs
  src/umessage.rs
Labels: enhancement

#150 Remove obsolete function
  src/uattributes.rs
Labels: enhancement

#153 Add helpers for checking UUri for wildcard usage
  src/uri.rs
Labels: enhancement

#155 Add Debug impl for ComparableListener
  src/utransport.rs
Labels: enhancement

#158 Use markdown for README
  .github/workflows/release.yaml
  Cargo.lock
  Cargo.toml
  README.adoc
  README.md
Labels: bug

#162 Add L2 API examples
  Cargo.lock
  Cargo.toml
  examples/simple_notify.rs
  examples/simple_publish.rs
  examples/simple_rpc.rs
  src/core.rs
  src/lib.rs
  src/local_transport.rs
Labels: enhancement

#163 Rename RequestHandler::invoke_method
  examples/simple_rpc.rs
  src/communication/in_memory_rpc_server.rs
  src/communication/rpc.rs
Labels: enhancement, breaking change

#165 Customize automatic generation of release notes
  .github/release.yml
Labels: enhancement, CI/CD

#167 Set resource ID to 0 while listening in InMemoryRpcServer.
  src/communication/in_memory_rpc_server.rs
  src/uri.rs
Labels: bug

#168 Fix nightly testing of all feature combinations
  Cargo.toml
Labels: bug, CI/CD

#169 Empty Authority field implies local UUri
  src/communication.rs
  src/umessage.rs
  src/uri.rs
  src/uuid.rs
Labels: bug

#172 Include examples in package being published
  Cargo.lock
  Cargo.toml
Labels: bug, CI/CD
