Repository eclipse-uprotocol/up-rust, pull requests merged in 2024-08, with the labels that each got.

#173 Cosmetics - fix dev container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement

#174 Add msrv check to release flow
  .github/workflows/README.md
  .github/workflows/release.yaml
Labels: CI/CD

#175 Increase test coverage for InMemoryRpcClient
  src/communication.rs
  src/communication/in_memory_rpc_client.rs
Labels: enhancement

#181 Add nightly check for compatibility with up-spec
  .github/workflows/README.md
  .github/workflows/check-up-spec-compatibility.yaml
Labels: enhancement, CI/CD

#184 Include requirements tracing in nightly up-spec compatibility check
  .github/actions/run-oft/README.md
  .github/actions/run-oft/action.yaml
  .github/workflows/check-up-spec-compatibility.yaml
  .github/workflows/requirements-tracing.yaml
Labels: enhancement, CI/CD

#188 Exclude L1 and L3 requirements from OFT check
  .github/actions/run-oft/action.yaml
Labels: enhancement, CI/CD

#189 Make run-oft Action more flexible
  .github/actions/run-oft/action.yaml
  .github/workflows/requirements-tracing.yaml
Labels: enhancement, CI/CD

#191 Install JDK if necessary only
  .github/actions/run-oft/action.yaml
  .github/actions/run-oft/determine_java_executable.sh
  .github/workflows/check-up-spec-compatibility.yaml
  .github/workflows/requirements-tracing.yaml
Labels: enhancement, CI/CD

#192 Assume PROTOBUF_WRAPPED_IN_ANY if format is unspecified
  src/umessage.rs
Labels: bug

#190 Use GitHub variable to define OFT file patterns
  .github/workflows/check-up-spec-compatibility.yaml
  .github/workflows/nightly.yaml
  .github/workflows/requirements-tracing.yaml
Labels: enhancement, CI/CD

#193 Use standard OpenFastTrace GitHub Action
  .github/actions/run-oft/README.md
  .github/actions/run-oft/action.yaml
  .github/actions/run-oft/determine_java_executable.sh
Labels: enhancement, CI/CD

#194 Fix OFT report file format
  .github/actions/run-oft/action.yaml
Labels: bug, CI/CD

#195 Improve usability of UPayload
  src/communication.rs
  src/umessage.rs
Labels: enhancement

#196 Use released version of OFT Action
  .github/actions/run-oft/action.yaml
Labels: enhancement, CI/CD

#197 Use separate repo variable for up-rust file patterns
  .github/workflows/check-up-spec-compatibility.yaml
  .github/workflows/nightly.yaml
Labels: enhancement, CI/CD

#198 Include tracing report in release artifacts
  .github/workflows/license-report.yaml
  .github/workflows/release.yaml
Labels: enhancement, CI/CD
