Repository eclipse-uprotocol/up-rust, pull requests merged in 2024-06, with the labels that each got.

#120 Re-add support for mapping payload format to string
  src/uattributes.rs
  src/uattributes/upayloadformat.rs
Labels: bug

#123 Include ucode.proto to build script
  build.rs
  src/ustatus.rs
Labels: bug

#125 Migrate UUIDBuilder to use UUIDv7
  src/lib.rs
  src/uattributes.rs
  src/uattributes/uattributesvalidator.rs
  src/umessage/umessagebuilder.rs
  src/uuid.rs
  src/uuid/README.md
  src/uuid/uuidbuilder.rs
Labels: enhancement

#126 Use custom parameter types in L2 API
  src/communication.rs
  src/communication/notification.rs
  src/communication/pubsub.rs
  src/communication/rpc.rs
Labels: enhancement

#127 Add missing usubscription type export, minor qol functions
  src/communication.rs
  src/communication/rpc.rs
  src/core/usubscription.rs
  src/umessage.rs
  src/uri.rs
Labels: bug, enhancement

#132 comm_status() now takes a UCode
  src/umessage/umessagebuilder.rs
Labels: enhancement

#133 Add missing usubscription proto export
  src/core/usubscription.rs
Labels: bug
