Repository eclipse-uprotocol/up-rust, pull requests merged in 2025-06, with the labels that each got.

#257 Minor update and improvement to devcontainer setup
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement

#258 Add helper function for validating filter criteria
  src/lib.rs
  src/utransport.rs
Labels: enhancement

#265 Fix latest spec compatibility job
  .github/workflows/latest-up-spec-compatibility.yaml
Labels: bug, CI/CD

#268 Fix up-rust version in README.md
  README.md
Labels: bug, documentation

#270 Restrict number of feature permutations to test
  Cargo.toml
Labels: bug, CI/CD
